---
- name: Ensure pre and post hook folders exist.
  file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: "0755"
    owner: root
    group: root
  with_items:
    - pre
    - post

- name: Create pre hook to stop services.
  template:
    src: stop_services.j2
    dest: /etc/letsencrypt/renewal-hooks/pre/stop_services
    owner: root
    group: root
    mode: "0750"
  when:
    - cert_item.deploy is defined
    - cert_item.deploy
  block:

    - name: Cert.Standalone - Create deploy hook to deploy certificates.
      ansible.builtin.template:
        src: deploy_certificates.j2
        dest: "{{ certbot_deployhook }}"
        owner: root
        group: root
        mode: "0750"

    - name: Cert.Standalone - Create deploy destination {{ cert_item.domains[0] }}
      loop: "{{ cert_item.deploy }}"
      when:
        - item.destcreate is defined
        - item.destcreate | bool
      ansible.builtin.file:
        path: "{{ item.dest }}"
        owner: "{{ item.destowner }}"
        group: "{{ item.destgroup }}"
        mode: "{{ item.destmode }}"
        state: directory

# ------ Firewall

- name: Cert.Standalone - Ensure HTTP port is open for webserver
  become: true
  register: certbot_http_open
  notify: Close HTTP Port
  when:
    - certbot_create_method == "standalone"
    - not letsencrypt_cert.stat.exists
  ansible.posix.firewalld:
    service: "http"
    permanent: true
    state: enabled
    immediate: true

# ------ Dry Run

- name: Cert.Standalone - Print Certbot command
  when:
    - certbot_dryrun
  ansible.builtin.debug:
    msg:
      - "Certbot Command:"
      - "----------------"
      - "{{ certbot_create_command }}"
      - "----------------"

# ------ Back to Jeff

- name: Cert.Standalone - Generate new certificate if one doesn't exist.  # noqa: no-changed-when
  become: true
  register: certbot_create
  when:
    - certbot_create_standalone_stop_services is defined
    - certbot_create_standalone_stop_services

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  register: certbot_create
  changed_when: "'no action taken' not in certbot_create.stdout"

# ------


- name: Cert.Standalone - Report on certificate creation
  ansible.builtin.debug:
    var: certbot_create
