---
- name: Certbot.Cert.Webroot - Check if certificate already exists.
  become: true
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first }}/cert.pem
  register: letsencrypt_cert

- name: Certbot.Cert.Webroot - Create webroot directory if it doesn't exist yet
  ansible.builtin.file:
    path: "{{ cert_item.webroot | default(certbot_webroot) }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Certbot.Cert.Webroot - Generate new certificate if one doesn't exist.  # noqa: no-changed-when
  become: true
  register: certbot_create_output
  when:
    - not letsencrypt_cert.stat.exists
  ansible.builtin.command:
    cmd: "{{ certbot_create_command }}"
