---
# tasks file for certbot

- name: Certbot.Main - Handoff to preflight task.
  ansible.builtin.include_tasks: preflight.yml

- name: Certbot.Main - Handoff to preflight RHEL task.
  when: ansible_os_family == 'RedHat'
  ansible.builtin.include_tasks: preflight_rhel.yml

# --------

- name: Certbot.Main - Handoff to TLS task
  ansible.builtin.include_tasks: tls.yml
  when:
    - certbot_install_rootcerts
    - certbot_install_rootcerts is defined and certbot_install_rootcerts | list

- name: Certbot.Main - Handoff to install task (package method).
  ansible.builtin.include_tasks: install_package.yml
  when: certbot_install_method == 'package'

- name: Certbot.Main - Handoff to install task (source method).
  ansible.builtin.include_tasks: install_source.yml
  when: certbot_install_method == 'source'

- name: Certbot.Main - Handoff to install task (snap method).
  ansible.builtin.include_tasks: install_snap.yml
  when: certbot_install_method == 'snap'

# --------

- name: Certbot.Main - Handoff to standlone cert creation task.
  ansible.builtin.include_tasks: create_cert_standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- name: Certbot.Main - Handoff to Webroot cert creation task.
  ansible.builtin.include_tasks: create-cert-webroot.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'webroot'
  loop_control:
    loop_var: cert_item

# - name: Certbot.Main - Handoff to AutoRenew (cron) task.
#   ansible.builtin.import_tasks: renew_cron.yml
#   when: certbot_auto_renew
