---

- name: PreFlight - Test variable certbot_install_method
  become: false
  ansible.builtin.assert:
    that:
      - certbot_install_method is defined
      - certbot_install_method is string
      - certbot_install_method in [ "package", "source", "snap" ]
    quiet: true

- name: PreFlight - Test variable certbot_create_method
  become: false
  ansible.builtin.assert:
    that:
      - certbot_create_method is defined
      - certbot_create_method is string
      - certbot_create_method in [ "standalone", "apache", "webroot" ]
    quiet: true

- name: PreFlight - Test variable certbot_create_method
  become: false
  when: certbot_create_method == "webroot"
  ansible.builtin.assert:
    that:
      - certbot_create_method is defined
      - certbot_create_method is string
      - certbot_create_method in [ "standalone", "apache", "webroot" ]
    quiet: true

- name: PreFlight - Test source variables
  become: false
  when: certbot_install_method == "source"
  ansible.builtin.assert:
    that:
      - certbot_repo is defined and certbot_repo is string and certbot_repo | length >= 1
      - certbot_version is defined and certbot_version is string and certbot_version | length >= 1
      - certbot_keep_updated is defined and certbot_keep_updated is bool
      - certbot_dir is defined and certbot_dir is string and certbot_dir | length >= 1
    quiet: true

- name: PreFlight - Test pre and post hooks
  become: false
  when: certbot_install_method == "source"
  ansible.builtin.assert:
    that:
      - certbot_repo is defined and certbot_repo is string and certbot_repo | length >= 1
      - certbot_version is defined and certbot_version is string and certbot_version | length >= 1
      - certbot_keep_updated is defined and certbot_keep_updated is bool
      - certbot_dir is defined and certbot_dir is string and certbot_dir | length >= 1
    quiet: true

# - name: Debug Var
#   ansible.builtin.debug:
#     var: item.domains
#   loop: "{{ certbot_certs }}"

# TODO: Install required DNS package or delegate to local

- name: PreFlight - DNS Lookup test
  become: false
  ansible.builtin.debug:
    msg: "{{ lookup('community.general.dig', 'google.co.uk.') }}"
  delegate_to: localhost
  when:
    - certbot_test_dns | bool
