---
# See: https://github.com/geerlingguy/ansible-role-certbot/issues/107
- name: Certbot.PreFlight.RHEL - Configure RHEL based systems for Ansible
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version | int >= 8
  block:

    - name: Certbot.PreFlight.RHEL - Ensure dnf-plugins are installed on CentOS 8+.
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Certbot.PreFlight.RHEL - Configure CentOS 8 for Ansible Package management
      when: ansible_facts['distribution_version'] is version('8.2', '<=')
      block:

        - name: Certbot.PreFlight.RHEL - Enable DNF module for CentOS 8.3+.  # noqa: command-instead-of-shell
          register: dnf_module_enable
          changed_when: false
          when: ansible_facts['distribution_version'] is version('8.3', '>=')
          ansible.builtin.shell:
            cmd: dnf config-manager --set-enabled powertools

        - name: Certbot.PreFlight.RHEL - Enable DNF module for CentOS 8.0–8.2.  # noqa: command-instead-of-shell
          changed_when: false
          register: dnf_module_enable
          ansible.builtin.shell:
            cmd: dnf config-manager --set-enabled PowerTools
